### ISSUE TITLE
Network lane flags - some infos

### ISSUE THREAD

**Issue by originalfoo** [ronyx69/cslmodding#1]
On the website here: https://cslmodding.info/asset/network/#flags

The start/end one way left/right flags are possibly for traffic lights, so that relevant props can be displayed.

![52598348-58e0d580-2e4d-11e9-9eec-b2f94a834d78](https://user-images.githubusercontent.com/1386719/52901674-7243a200-31fe-11e9-8897-cba97937ed05.gif)

Those traffic lights are part of the [UK Roads Revived assets](https://steamcommunity.com/workshop/browse/?appid=255710&searchtext=uk+roads+revived&childpublishedfileid=0&browsesort=textsearch&section=home).

**Comment by originalfoo** [comment]
The ```Blocked``` flag on network segments is used to indicate blocked road segments (it affects pathfinding and vehicle AIs).

A building fire will cause nearby segments to become blocked, causing traffic to route round it. Once issue is resolved (eg. fire put out) the segment is unblocked by the relevant service AI.

Emergency vehicles ignore the blocked flag.

I suspect, but haven't yet tested, that building collapses will mark adjacent segments blocked too.

**Comment by ronyx69** [comment]
I have figured out at least part of the StartOneWayLeft and StartOneWayRight flags.

![Cities_ZfkQOUDEZk](https://user-images.githubusercontent.com/22746713/81493667-a0e5e680-92a2-11ea-845f-6ef63c0e9e08.png)
all lanes on the split off right road have StartOneWayLeft and all the ones on the split off right road have StartOneWayRight

This is my current attempt to word it which I will add to cslm:

**StartOneWayLeft**
Active for lanes which begin after splitting off from the right side of a one-way road at a significant enough angle, the same angle required for the previous lane to get the Right flag.

**StartOneWayRight**
Active for lanes which begin after splitting off from the left side of a one-way road at a significant enough angle, the same angle required for the previous lane to get the Left flag.

**Comment by originalfoo** [comment]
@kianzarrin can probably give more info on the flags as he's been digging in to that stuff a lot recently with the mods he's working on.
