### ISSUE TITLE
Network segment flag - StopLeft and StopRight flags

### ISSUE THREAD

**Issue by ghost** [ronyx69/cslmodding#4]
The two flags are always set false for elevated and bridge segments, no matter there is a bus stop or not. Haven't tested on slope and tunnel.
Get frustrated again by game mechanics trying to make my own road.

**Comment by originalfoo** [comment]
You can use elevated stops enabler mod to overcome that limitation I think.

**Comment by ghost** [comment]
> You can use elevated stops enabler mod to overcome that limitation I think.

I tried but it doesn't seem to work.

**Comment by ronyx69** [comment]
AFAIK stops can't be placed on elevated roads without the mod.  So there's nothing relevant to add to CSLM regarding this.
